version: '3.7'

services:

  main:
    build:
      context: .
      target: development
    image: nest-ir:1.0
    ports:
      - 3002:3000
    environment:
      DOTENV_CONFIG_PATH: docker/env/env.example
    volumes:
      - ./:/app
      #- ./docker/supervisor:/etc/supervisor/conf.d/

    networks:
      - shared_net
    command: yarn run start:dev
    
networks:
  shared_net:
    external: true

# docker-compose up --build -V

